### ISSUE TITLE
BOM (bill of material) 

### ISSUE THREAD

**Issue by Rixxxi** [sandor-ino/MARLIN-LABISTS-X1-SANDOR-MOD#1]
### Is your feature request related to a problem? Please describe.

Hi,
first of all: I'm still new to working with GitHub and I'm not sure if there is an other/better way than to raise an "issue" to post this kind of comment/request. If so, please let me know.

I came accross your project and would love to build it.
As my experience with Arduinos etc. is as "good" as with GitHub, I'm not sure which Arduino version and other components I will need.  If course I see some electronics model specifications in the wiring diagram, but it still leaves me with a feeling of not knowing which components I should get **_exactly_**.
For example: There are many Arduino versions around. AFAIK some of them have different chipsets even if they have the same model name. Does this make any difference? Is a specific model or chipset needed or to be prefered?

### Describe the feature you want

Basicly a simple and clear BOM would help people like me :-)

Thank you,
Rixi

**Comment by sandor-ino** [comment]
First of all, thank you for your interest in the project, I am not expert but I think this section is used to report any malfunctions, but never used it. In the project there are all the elements that are needed to make it, even in the videos you will find useful information, there is a specially missing some things such as programming Arduino or the USB driver of the printer. I can give you ultrily indications but the step by step procedure I would not be able to reconstruct it.
